url: "https://blog.alecw.net" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "ALC;THGHT" # the name of your site, e.g. ACME Corp.

theme_config:
    date_format: "%m-%d-%Y"
